### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust-test-runner#28]
There should be tests to verify the test runner behavior from an input/output perspective. The best option is probably to mimic what other tracks are doing, and having a `tests` directory with some golden tests (see https://github.com/exercism/prolog-test-runner/tree/main/tests) and then having a [`bin/run-tests.sh`](https://github.com/exercism/prolog-test-runner/blob/main/bin/run-tests.sh) and [`bin/run-tests-in-docker.sh`](https://github.com/exercism/prolog-test-runner/blob/main/bin/run-tests-in-docker.sh] script files. These are then used in a [CI workflow](https://github.com/exercism/prolog-test-runner/blob/main/.github/workflows/ci.yml).

**Comment by senekor** [comment]
I think this was completed with https://github.com/exercism/rust-test-runner/pull/41, right?

**Comment by ErikSchierboom** [comment]
Correct
