### ISSUE TITLE
All tests successful on my machine, but FAIL or TIMEOUT on the website.

### ISSUE THREAD

**Issue by iago-lito** [exercism/rust-test-runner#30]
This happens on my 4th iteration to Forth in the Rust track: https://exercism.org/tracks/rust/exercises/forth/solutions/iago-lito
![exercism org_tracks_rust_exercises_forth_iterations](https://user-images.githubusercontent.com/10091387/135875356-cfc29102-5b49-4177-b168-741f6ad629b0.png)

What could be wrong?

**Comment by iago-lito** [comment]
> Are you using any external crates in this solution?

No I'm not. Thank you for investigating this :) For some reason I didn't get the github notification about progress on this issue, I'll try to keep updated. Feel free to ask for more detail if you need.

**Comment by iago-lito** [comment]
@senekor Thank you for reviving / closing this ;) How should I've been able to tell that this special test file existed since `cargo test` did not tell?

**Comment by senekor** [comment]
Yeah, it's difficult to tell. I think I was confused myself when I first solved the exercise. `cargo test` technically does tell you how many tests were skipped. But it's visually very hard to notice. The output of `cargo-nextest` is better, if you're interested in that.

We might consider adding a note about this in the exercise instructions.
