### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust-test-runner#34]
While trying to build the Rust test runner, I get the following error as part of the `RUN /rust-test-runner/bin/generate-registry.sh` command in the Dockerfile:

```
#21 88.61 Caused by:
#21 88.61   failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/out-6.1.0/Cargo.toml`
#21 88.61 
#21 88.61 Caused by:
#21 88.61   failed to parse the `edition` key
#21 88.61 
#21 88.61 Caused by:
#21 88.61   supported edition values are `2015` or `2018`, but `2021` is unknown
```

@dhovart do you know how to fix this?

**Comment by dhovart** [comment]
I'm going to look at it today. It may be the `local-registry` command that is failing because it's not aware of the new rust 2021 edition

**Comment by dhovart** [comment]
cargo-local-registry relies on an old version of cargo as a dependency, where "2021" is not considered a valid edition.
I'm working on a PR to use the latest cargo version.
