### ISSUE TITLE
"test runner crates local registry" does not container newer version of dependency

### ISSUE THREAD

**Issue by ondrej-ivanko** [exercism/rust-test-runner#39]
Hi folks,

I ran to some issues with test runner. I'm using crate for completing exercise [ResistorColor](https://exercism.org/tracks/rust/exercises/resistor-color) and I'm running into issues with test runner as it seems to be using repository of probably cached versions of various crates. And this repo does not contain latest version of `heck` package (0.3.3), which is dependency of crate `strum_macros`. I tried to manually set heck to lower version in Cargo.toml (0.3.2), that is in the local repository, but Cargo keeps adding to Cargo.lock latest version of heck 0.3.3. Which raises error in test runner.
Or maybe the issue is that runner can't resolve regex version matching for heck...

![Screenshot_20211204_160736](https://user-images.githubusercontent.com/44980578/144714522-54ff1e9a-68b5-4339-99fe-e398606f23fd.png)

I couldn't find solution to force Cargo.lock use version in Cargo.toml.

**Comment by coriolinus** [comment]
Related: https://github.com/exercism/rust-test-runner/issues/37.

**Comment by senekor** [comment]
This is most likely caused by `Cargo.toml` being submitted as part of the solution. Not submitting `Cargo.toml` usually solves this problem.

As a side note, it's possible to pin the exact version in `Cargo.toml` using the syntax:
```
heck = "=0.3.0"
```

Feel free to ping if you have more questions.
