### ISSUE TITLE
I keep receiving this error when I try to resolve the exercise in the Exercism's in-browser editor

### ISSUE THREAD

**Issue by meli-tortelli** [exercism/rust-test-runner#44]
Hi guys...

So I just started studying rust and when I try to evaluete my test I receive this same error, but I don't know what can be. For what i looked up everything looks ok on my code... Someone can help me with that? I would really appreciate the help. ;)

![image](https://user-images.githubusercontent.com/56207729/149616150-79c048ef-776d-40b4-8840-adf6883971c9.png)

**Comment by coriolinus** [comment]
You changed the function signature; the function should not be named
`main`.

**Comment by meli-tortelli** [comment]
oooh ok, I get it. thanks, coriolinus! I wasn't understanding, it worked out now.  ;p heheheh
