### ISSUE TITLE
Upload Cargo.lock in Exercism editor

### ISSUE THREAD

**Issue by LyndonGingerich** [exercism/rust-test-runner#72]
I'm taking the 12in23 challenge, so I use the online editor so I don't have to install a dozen languages and barely use them. Whenever I run tests on Rust programs, I get a message:
```
WARNING: student did not upload Cargo.lock. This may cause build errors.
```
How am I supposed to upload Cargo.lock? I don't see a button for it anywhere. Does it mean Cargo.toml? But I can already see that file in the editor, so the build agent must also have access to it.

**Comment by StEvUgnIn** [comment]
> I'm taking the 12in23 challenge, so I use the online editor so I don't have to install a dozen languages and barely use them. Whenever I run tests on Rust programs, I get a message:
> 
> ```
> WARNING: student did not upload Cargo.lock. This may cause build errors.
> ```
> 
> How am I supposed to upload Cargo.lock? I don't see a button for it anywhere. Does it mean Cargo.toml? But I can already see that file in the editor, so the build agent must also have access to it.

Use the following instruction in the terminal:

```shell
exercism submit src/lib.rs Cargo.toml
``` 

Explanation: Cargo.lock is directly compiled from Cargo.toml on your machine. Instead, use Cargo.toml which is the source file needed by the test runner to install external crates and test your solutions.

**Comment by senekor** [comment]
@StEvUgnIn The test runner doesn't emit this error message anymore. The error message is now:

```
WARNING: student did not upload Cargo.toml. This may cause build errors.
```

So it correctly refers to `Cargo.toml`.

Don't use `exercism submit src/lib.rs Cargo.toml`. Instead, just use `exercism submit`. The exercises are already preconfigured to include these files in the submission.

You may need to specify the files explicitly if you split your solutions into multiple files, in addition to `lib.rs`.

**Comment by StEvUgnIn** [comment]
@senekor Using submit does not always add Cargo.toml to the submission (e. g., `reverse-string`).

**Comment by StEvUgnIn** [comment]
After a peek of `.exercism/config.json`, I have noticed that all exercises add `Cargo.toml` to the submission:
```json
"files": {
    "solution": [
      "src/lib.rs",
      "Cargo.toml"
    ],
}
```

It appears that the official vscode extension only submits `src/lib.rs` in my case when using the option submit.

```vscode
> Exercism-CLI: Submit your solution
```

**Comment by senekor** [comment]
I didn't even know this extension existed, its commit history [doesn't inspire confidence](https://github.com/exercism/vscode-exercism-cli/commits/main/).

I would recommend to just use the CLI directly.

**Comment by LyndonGingerich** [comment]
> I use the online editor

--me

> Use the following instruction in the terminal:

> Cargo.lock is directly compiled from Cargo.toml **on your machine**.

--@StEvUgnIn 

I think we may have a slight misunderstanding.

**Comment by LyndonGingerich** [comment]
Title edited for clarity.

**Comment by senekor** [comment]
Do not upload Cargo.lock. This issue is irrelevant now, the misleading error message is not emitted anymore. Just use the online editor normally or the CLI as documented and you should be fine. Please open another issue / ask on the forum if you encounter other problems.
