### ISSUE TITLE
Acronym exercise: error: failed to select a version for the requirement `regex = "^1.8.4"` (locked to 1.9.1)

### ISSUE THREAD

**Issue by TheLinuxEnthusiast** [exercism/rust-test-runner#74]
Hi,

I'm getting the below error when pushing my code to the exercism rust runner. I'm trying to push a solution for the Acronym exercise.

I tried removing the regex crate v1.9.1 and then adding v1.8.4 manually to my Cargo.toml file but still the same issue. All of my tests pass locally without issue.

""""
We received the following error when we ran your code:

error: failed to select a version for the requirement `regex = "^1.8.4"` (locked to 1.9.1)
candidate versions found which didn't match: 1.8.4
location searched: `/opt/test-runner/local-registry` index (which is replacing registry `crates-io`)
required by package `acronym v1.7.0 (/mnt/exercism-iteration)`
perhaps a crate was updated and forgotten to be re-vendored?
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
"""

If you want to look at my code you can find it under my own github profile here: 

https://github.com/TheLinuxEnthusiast/exercism-df/tree/master/rust/acronym

Thanks,

Darren

**Comment by senekor** [comment]
@TheLinuxEnthusiast I think the interesting part is:

> (locked to 1.9.1)

Could it be that you provided the `Cargo.lock` file in your submission? If so, you might try making another submission without the lockfile. Or you could pin the exact version with `regex = "=1.8.4"`

**Comment by TheLinuxEnthusiast** [comment]
Yeah that was it! Thanks
