### ISSUE TITLE
Output compilation errors

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust-test-runner#9]
While working with the Rust experiment exercises, having a compile error would show the following output:

```
no tests detected; probable build failure
```

It would be great if we could show the actual compilation error, which would help the student solve the issue. Note that the compilation error should be output in the root `message` property and the root `status` property should be set to `"error"`. For more information, see the [test runner interface description](https://github.com/exercism/automated-tests/blob/master/docs/interface.md#top-level).

**Comment by coriolinus** [comment]
Agree that would be better UX, but it's not a simple change. I'll think
about it some more, but I can't promise anything concrete soon.

**Comment by ErikSchierboom** [comment]
Sure. Thanks for the quick response! Many tracks found this to be surprisingly hard.

**Comment by coriolinus** [comment]
What's in the secondary output file? I thought that compilation messages
were already redirected there?

**Comment by ErikSchierboom** [comment]
The second output file's goal is for debugging purposes, and as such is meant for the maintainer, not the student. This issue is about showing the compilation error to the student, which is in the `results.json` file. Does that help?

**Comment by ErikSchierboom** [comment]
Closed by #11
